services:
#####################################
# PostgreSQL
#####################################
  db:
    container_name: postgredb
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    healthcheck:
      test: ["CMD", "/usr/local/bin/pg_isready", "-q", "-d", "$POSTGRES_DB", "-U", "$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./docker/pg/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  app:
    profiles: [debug]
    container_name: fastify-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    # command: tail -f /dev/null # keep container running for checking inside
    command: pnpm start
    ports:
      - 3000:3000
  drizzle_studio:
    container_name: drizzle_studio
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/drizzle-studio.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    network_mode: host # use host network for drizzle studio cause isolate network within container is not supported
    # command: tail -f /dev/null # keep container running for checking inside
    command: pnpm exec drizzle-kit studio --port 3001

volumes:
  pgdata: