services:
#####################################
# PostgreSQL
#####################################
  db:
    container_name: postgredb
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    healthcheck:
      test: ["CMD", "/usr/local/bin/pg_isready", "-q", "-d", "$POSTGRES_DB", "-U", "$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./docker/pg/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  app:
    profiles: [debug]
    container_name: fastify-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    # command: tail -f /dev/null # keep container running for checking inside
    command: pnpm start
    ports:
      - 3000:3000
  drizzle_studio:
    container_name: drizzle_studio
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/drizzle-studio.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    network_mode: host # use host network for drizzle studio cause isolate network within container is not supported
    # command: tail -f /dev/null # keep container running for checking inside
    command: pnpm exec drizzle-kit studio --port 3001
  minio-s3-compatible:
    container_name: minio-s3
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server --console-address ":9001" /data
    volumes:
      - minio_storage:/data
  # smtp4dev:
  #   image: rnwood/smtp4dev:v3
  #   restart: unless-stopped
  #   ports:
  #     # Change the number before : to the port the web interface should be accessible on
  #     - '8081:80'
  #     # Change the number before : to the port the SMTP server should be accessible on
  #     - '25:25'
  #     # Change the number before : to the port the IMAP server should be accessible on
  #     - '143:143'
  #   volumes:
  #     # This is where smtp4dev stores the database..
  #       - smtp4dev-data:/smtp4dev
  #   environment:
  #     # Uncomment to customise these settings
  #     # This is not a complete list of the available settings.
  #     # See the documentation in appsettings.json for a full list.

  #     #Specifies the virtual path from web server root where SMTP4DEV web interface will be hosted. e.g. "/" or "/smtp4dev"
  #     #- ServerOptions__BasePath=/smtp4dev

  #     #Specifies the server hostname. Used in auto-generated TLS certificate if enabled.
  #     - ServerOptions__HostName=smtp4dev

  #     #Locks settings from being changed by user via web interface
  #     #- ServerOptions__LockSettings=true

  #     #Specifies the path where the database will be stored relative to APPDATA env var on Windows or XDG_CONFIG_HOME on non-Windows. Specify "" to use an in memory database.
  #     #- ServerOptions__Database=database.db

  #     #Specifies the number of messages to keep
  #     #- ServerOptions__NumberOfMessagesToKeep=100

  #     #Specifies the number of sessions to keep
  #     #- ServerOptions__NumberOfSessionsToKeep=100

  #     #Specifies the TLS mode to use. None=Off. StartTls=On demand if client supports STARTTLS. ImplicitTls=TLS as soon as connection is established.
  #     #- ServerOptions__TlsMode=None

  #     #Specifies the TLS certificate to use if TLS is enabled/requested. Specify "" to use an auto-generated self-signed certificate (then see console output on first startup)
  #     #- ServerOptions__TlsCertificate=

  #     #Sets the name of the SMTP server that will be used to relay messages or "" if messages should not be relayed
  #     #- RelayOptions__SmtpServer=

  #     #Sets the port number for the SMTP server used to relay messages.
  #     #- RelayOptions__SmtpPort=25

  #     #Specifies a comma separated list of recipient addresses for which messages will be relayed. An empty list means that no messages are relayed.
  #     #- RelayOptions__AllowedEmailsString=

  #     #Specifies the address used in MAIL FROM when relaying messages. (Sender address in message headers is left unmodified). The sender of each message is used if not specified.
  #     #- RelayOptions__SenderAddress=

  #     #The username for the SMTP server used to relay messages. If "" no authentication is attempted.
  #     #- RelayOptions__Login=

  #     #The password for the SMTP server used to relay messages
  #     #- RelayOptions__Password=

  #     #Specifies the port the IMAP server will listen on - allows standard email clients to view/retrieve messages
  #     #"ServerOptions__ImapPort"=143

volumes:
  pgdata:
  minio_storage:
  smtp4dev-data: